### ISSUE TITLE
[Spinner] Fix/Add loading Spinners

### ISSUE THREAD

**Issue by josephmiclaus** [fhstp-mfg/mobilot#165]
Components might trigger HTTP requests, which should show a loading spinner **within** the component itself and ( if necessary ) lock everything else until the response arrives and is handled.

### Umbrella
- [x] Home
  - [x] All Mobiduls list
  - [x] Nearby Mobiduls list
  - [x] Own Mobiduls list
- [ ] Mobidul
  - [ ] Station lists (All stations, category stations list)
- [ ] MobidulCreator
  - [ ] Create Mobidul button
  - [ ] Save Mobidul button
  - [ ] Save categories button
  - [ ] Save menu button
  - [ ] Save options button
- [ ] StationCreator
  - [ ] Save Station button
  - [ ] Cancel Station button
  - [ ] Copy Station button 
  - [ ] Delete Station button
- [ ] Play
    - [ ] Join Mobidul button
- [ ] Menu
  - [ ] Reset Rally dialog / button

### Notes
It might be a good idea to implement loading spinner functionality within recurring components such as button.

Please feel free to comment/edit if there are missing components.

Thank you !
